### PR TITLE
colab torch 2 update

### PR DESCRIPTION
**Pull request by nawnie**
there's a lot, here's the highlights as long as your gdrive mounts fast you can start training in about a minute now, speed and memory utilization seem to be better but it is not stress tested yet. it can do batch of 8 still no problem. 

progress bars fixed, need for colab to crash fixed

### CODE REVIEW

**Comment by nawnie** [comment]
Maybe, I don't play with that part of the code just the cells, I can try to
remove it but it's always used high ram to break down the ckpt into
diffusers

**Comment by nawnie** [comment]
Remember highram in colab is like 12gb.

**Comment by victorchall** [comment]
Normal ram is 12GB, high ram is much more. 

If it runs normal I don't want the popup because I will get pinged a dozen times "hey I got this error when I started colab" and people will think something is wrong.

**Comment by nawnie** [comment]
Ok ill try it when I wake up

**Comment by victorchall** [comment]
I fixed the high memory required warning after merge

**Comment by nawnie** [comment]
Sounds good to me I'll stress test tonight cause i do believe we'll find a
case that needed high ram, it may of been 2.1 training it may of been the
breaking down diffusers, if I find it ill add a markdown.

May even of only been an issue due to how we had to work around py 3.9 and
be gone now

**Pull request merged**
