### PR TITLE
warn on chronically underfilled aspect ratio buckets

### PR DESCRIPTION
**Pull request by damian0815**
Log a warning and suggestion to reduce batch size or add more images if an aspect ratio bucket's runt size causes the effective multiplier for images at that aspect ratio to be >1.5

### CODE REVIEW

**Comment by damian0815** [comment]
example output:
```
 * Aspect ratio bucket (512, 512) has only 11 images. At batch size 10 this makes for an effective multiplier of 1.8, which may cause problems. Consider adding up to 9 more images for aspect ratio 1:1, or reducing your batch_size.
 * Aspect ratio bucket (384, 640) has only 6 images. At batch size 10 this makes for an effective multiplier of 1.7, which may cause problems. Consider adding up to 4 more images for aspect ratio 3:5, or reducing your batch_size.
 * Aspect ratio bucket (640, 384) has only 3 images. At batch size 10 this makes for an effective multiplier of 3.3, which may cause problems. Consider adding up to 7 more images for aspect ratio 5:3, or reducing your batch_size.
 * Aspect ratio bucket (576, 448) has only 1 images. At batch size 10 this makes for an effective multiplier of 10.0, which may cause problems. Consider adding up to 9 more images for aspect ratio 9:7, or reducing your batch_size.
 ** Dataset 'train': 7 batches, num_images: 70, batch_size: 10
```

**Review by victorchall — COMMENTED** [review]
Could this instead leverage something like report_image_train_item_problems?  I

**Comment by damian0815** [comment]
oooh. i get it. actually the "bucketing" logic should be pretty simple, it's just grouping by the target_wh property of the ImageTrainItem then doing a modulo against the batch size. yeah, makes sense, i'll do that.

**Comment by victorchall** [comment]
Yeah I'm not sure that farey stuff is really necessary.

**Comment by Alex-GZ** [comment]
Is there really a confirmed issue with the "runt" batches? In the code there is a loss multiplier compensating for repeated images. I.e. if  a batch has 1 image duplicated 10 times, it will be assigned a loss multiplier of 0.1 so the result will be completely the same math-wise as if it was a single image batch (if we forget about differing timesteps, which shouldn't cause negative effects in this case)

**Comment by victorchall** [comment]
The loss compensation is admittedly a hack, there's no "proper" way to compensate, but old alternative was dropping the runts entirely which is not ideal and was causing me giant headaches explaining to people.  I also had it scaling the gradients by runt_size/batch_size but that's fairly slow.  I may do another comparison or careful test on scaling grads vs scaling loss.  Again, neither of those are probably what you'd call "proper", right solution is adding data so the runt issue just sort of vanishes via shuffling.

**Comment by Alex-GZ** [comment]
Shouldn't scaling loss have exactly the same result as scaling grad, provided there are no under-/overflows (which is unlikely with scales in range 0.1-1.0 I think)? And I actually see nothing wrong with both of these approaches, just curious what could be the reasons for it to work bad - it seems ok if averaged across epochs, it doesn't tilt the distribution in any specific direction etc.. IMHO a significant difference in resolution ratio in the dataset itself is the thing can have a negative impact on resulting model (and may need to be compensated; with additional crops or scales or whatever), but not the batch size / runting.

**Comment by victorchall** [comment]
Potentially the optimizer state will react differently.  Might need some more investigation tbh.

**Comment by damian0815** [comment]
> it seems ok if averaged across epochs

what this PR is trying to catch is situations where there are only say 1 or 2 images at a given aspect ratio but the batch size is say 6. in this case the multiplier on those images becomes effectively 3.0 (if there are two images) or even 6.0 (if there is only one image). moreover this will not be avaraged across the epochs - *every epoch* you'll get 3 (or 6) copies of this image.

**Comment by damian0815** [comment]
@victorchall i refactored where the check happens as you suggested. i decided to shuffle about the logic for resolving items slightly, since the check for undefilled buckets needs to happen after the validation split has been claimed

**Review by victorchall — APPROVED** [review]

**Pull request merged**
