### PR TITLE
Colab Wip it runs 100% 

### PR DESCRIPTION
**Pull request by nawnie**
want to add a few things before done, dependencies updates, added  a json editor, reDOING inference cell. seems to be much quicker not calling a .py. install takes twice as long BUT i'm going to add a variable in first cell to not install dependencies for inference saving time if you plan to test with auto 1111.

Json editor makes a good ED tool as well so im going to add that in their to keeps us from needing a validator :P

### CODE REVIEW

**Comment by nawnie** [comment]
this branch has alot of commit history, so ill be adding to notebook main branch for actual pr just sharing what ive been working on.

**Comment by victorchall** [comment]
Ok, is the other PR dead then?

**Comment by nawnie** [comment]
No two different notebooks, one is ed tools this is the train ed2 colab. With kid less then a week away I want to share most up-to-date stuff I have incase I dissappear for a week or two. 

These all run but there not cleaned up, or I have commented to-dos in the code [like using xformers in the testing cell]

**Comment by victorchall** [comment]
Ah yeah you're right.

**Comment by victorchall** [comment]
FWIW I'm going to be making a react UI and I'll probably replace this, but fine with it for now.  Make sure to include something in the README on how to use it.

**Comment by nawnie** [comment]
shame had fun working on this project.

**Pull request closed without merging**
