### PR TITLE
 Add a linux setup file(generated by ChatGPT)

### PR DESCRIPTION
**Pull request by zhaoxy2850**

### CODE REVIEW

**Review by victorchall — COMMENTED** [review]
There are several errors in this.  Did you test it?

**Comment by victorchall** [comment]
Linux should be using torch2, the docker requirements files have almost everything needed, there's one command in start.h in the docker folder that runs a pip install.

**Comment by zhaoxy2850** [comment]
> There are several errors in this. Did you test it?

Oh sorry, I didn't see any errors. It works well in my environment Python 3.10.8, ubuntu22.04. 
I've installed it successfully using this script. And the training process went well too. 
Would you mind show me the errors?

**Comment by zhaoxy2850** [comment]
> Linux should be using torch2, the docker requirements files have almost everything needed, there's one command in start.h in the docker folder that runs a pip install.

Thank you for your information. I was running this project on a cloud platform. The framework it's using is miniconda(conda3). And they didn't support running in docker. So I had to install it manually.

**Comment by victorchall** [comment]
For one, the URL for the xformers wheel install does not exist.  You could not have run this without getting errors.  Run it and look at the outputs, this script will fail.

**Comment by zhaoxy2850** [comment]
Okay. I don't think this script is useful for this project now. Thank you for your time. I'm closing the pull request.

**Pull request closed without merging**
