### PR TITLE
Feature: Rolling save ckpt

### PR DESCRIPTION
**Pull request by damian0815**
Pass `--rolling_ckpt_save` to save a diffusers checkpoint to `ckpts/rolling-<name>-ep<epoch>` at the end of every epoch, that will be deleted and replaced at the end of the next epoch.

The intention with this feature is to minimise data loss if you're on an on-demand remote GPU and you get outbid in between saves - at most you lose one epoch's worth of training time.

### CODE REVIEW

**Comment by victorchall** [comment]
Checkpoints are saved periodically according to settings already.  What is the gain of making an extra copy with "rolling-" prepended that cannot already be accomplished without the change and a new CLI arg?

Is this about managing the high disk space usage every 1 epoch can cause?

**Comment by damian0815** [comment]
> Is this about managing the high disk space usage every 1 epoch can cause?

yep, that's it. i typically rent interruptible remote GPUs and if i have bad luck with being interrupted, can lose several hours worth of training.

**Comment by victorchall** [comment]
We discussed more on discord, I think this is a sort of specific use case and a plugin would be better than adding a CLI arg.

Feel free to PR a plugin for it though.  I think on_epoch_end could look at the log_folder and delete all but the most recent folder.  There's similar code used for resume_ckpt: "findlast".  You can add log_folder to the args list when calling plugin.on_epoch_end in train.py.   

The args list is open ended for now, as long as it is already in context in the training loop at the time of calling the plugin function, but I suppose at some point a better abstraction might be needed.  I'm not sure where the plugin system will go.

**Comment by damian0815** [comment]
Ok i rewrote it as a plugin. had to change some things about the way the plugin calls were done. i went ahead and added the `EveryDreamTrainingState` class we were discussing on discord.

**Review by victorchall — APPROVED** [review]

**Pull request merged**
