### PR TITLE
parallelizing image preloading

### PR DESCRIPTION
**Pull request by tjennings**
This approach saves about 10x on the time of this task for me locally.

### CODE REVIEW

**Comment by victorchall** [comment]
image
Spams my console then hangs, trying to load 125k COCO 2017 set.

**Comment by victorchall** [comment]
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "M:\ed2coreco\train.py", line 31, in <module>
    import torch.nn.functional as F
  File "M:\ed2coreco\venv\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "M:\ed2coreco\venv\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.```

**Comment by victorchall** [comment]
Not sure whats going on but torch is trying to init in each process and runs OOM?  My system has 64GB and trainer is using less than 2GB before it crashes.

**Comment by Alex-GZ** [comment]
It's a known problem when multi-threading Python code using pytorch (e.g.  explanation https://stackoverflow.com/questions/64837376/how-to-efficiently-run-multiple-pytorch-processes-models-at-once-traceback)
It commits (but not uses) a lot of memory due to multiple pytorch and nvidia DLL instances. Typical solution is to reduce the number of worker threads or to increase paging file size (the file itself won't be used,  OS just needs to be sure that this amount of memory may be allocated in the future)

IIRC, 8 pytorch data loader processes commit about 50 GB on my system. Maybe there should be a CLI argument for thread count instead of os.cpu_count()

**Comment by victorchall** [comment]
I have 64gb and I'm only using about 20 gb of system memory when attempting. 18gb of that is stuff that is already open on my system, only about 2-4gb in python at the it crashes. No rise in memory use either first, just outright dies.  64GB is more than enough to load the entire dataset to memory if it came down to that.  My page file is also set to system managed on a drive with 1.5TB free,

It also crashed on just a ~2400 image set, too, maybe a few gig of data but only like 1kb of data per image is really even stored in memory, actual binaries are read on the fly and then fall out of scope.

I've tried my own code using apply_async and no memory issues (see pooledload branch) but it has performance issues when loading more than a few thousand images unfortunately (way worse than single threaded).

I think there must be something else going on with this particular code and Windows.

**Pull request closed without merging**
