### PR TITLE
Add docker compose file

### PR DESCRIPTION
**Pull request by kelvie**
This makes it a lot easier to use locally on docker, and a lot easier to move files in/out, as well as save notebooks.

### CODE REVIEW

**Comment by victorchall** [comment]
Sorry for the delay.  Please review the CLA here and reply if you agree.

https://github.com/victorchall/EveryDream2trainer/blob/main/doc/EveryDream_CLA.txt

**Comment by kelvie** [comment]
@victorchall Yup, I agree.

**Comment by kelvie** [comment]
Another thing to note is that we may want to change the shm_size -- I'm not well-versed enough to know when this needs to be higher, but I ran into this issue with torch, and set it to 2GB (it defaults to 64MB):

https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container

**Comment by victorchall** [comment]
Thanks, I'll take a look into it.

**Comment by victorchall** [comment]
shm showed 64g when I checked it on a random runpod instance and 32g on an fairly fresh ubuntu image I installed.

**Comment by kelvie** [comment]
Ah, must be my local docker setup (which should be whatever the Arch package maintaner set by default):

```
~ sudo docker run --rm -it ubuntu                                                                                                        0 [16:40:17]
root@b3196254e19d:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         1.9T  1.6T  224G  88% /
tmpfs            64M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
/dev/nvme0n1p2  1.9T  1.6T  224G  88% /etc/hosts
tmpfs            32G     0   32G   0% /proc/asound
tmpfs            32G     0   32G   0% /proc/acpi
tmpfs            32G     0   32G   0% /proc/scsi
tmpfs            32G     0   32G   0% /sys/firmware
```

Or on runpod they configure it differently (never used runpod myself)

**Pull request merged**
